### ISSUE TITLE
Consider a section For Simple Saas Products to be promoted

### ISSUE THREAD

**Issue by devingray** [tighten/onramp#195]
Considering a tweet Matt sent out a few days ago
https://twitter.com/stauffermatt/status/1250989553533550592

When I was a new dev I loved to find a new tool, especially one that was used by the pros.

I think it could be a cool section in this project to list out a few of the most helpful tools to assist an app in production. 

This can be used for a few reasons.

1. Often times We get drawn into tools that are horrible to use and difficult to set up. I.E Jenkins CI takes a long time to get right but also takes a long time to onboard new people to the team. Therefore ChipperCi from the Laravel Community Has you covered. Or, your boss wants to know what an error is on Production because he has no time to waste while a developer is fixing an issue Flare has you covered. 

2. This may be a cool way to introduce these tools into the minds of the next wave of developers.

3. Laravel is Dope, so helping out our friends in the community is awesome. 

I have a small list of Laravel SAAS Tools that I personally use that have saved my behind a few times

1. Forge
2. Vapor
3. Envoyer
4. Flare
5. OhDear
6. Fathom
7. Oh Dear

And Of course Chipper CI the day it is released

**Comment by devingray** [comment]
Oh Dear!....
I Added Oh Dear Twice...

**Comment by MarcyLina** [comment]
Closing. Saas products are baked into appropriate modules as of now 🤓
