### ISSUE TITLE
Write out skills for all modules

### ISSUE THREAD

**Issue by tammytee** [tighten/onramp#224]
There are a large number of modules missing skills: 

- [x] Object-Oriented Programming
- [x] Basic JavaScript
- [x] Laravel Mix
- [x] Easy session-backed internal APIs
- [x] Deployments
- [x] Monitoring (e.g. Bugsnag)
- [x] Basic Testing
- [x] Laravel vs WordPress
- [x] Mapping the WordPress Concepts
- [x] Basic Dev-Ops
- [x] SQL and Databases

**Comment by MarcyLina** [comment]
All modules have skills set.
