### ISSUE TITLE
Parse through these resources and add where appropriate

### ISSUE THREAD

**Issue by mattstauffer** [tighten/onramp#23]
From here:
https://twitter.com/jonodonovan/status/1154762467979014144

Linked to here:
https://docs.google.com/document/d/13SzMxBBG7wQuq_yqaBhkyyRQlp5sYue14hBOBcvPnik/edit

Questions about adding these.
1. Are they any good?
2. Are they comprehensive?
3. Are they modern?
4. Is Udacity legit? (I remember them having some shady policies toward folks re-posting Jeffrey Way's content and others... is that resolved?)

Content:
----

**Computer Science**
https://udacity.com/course/intro-to-computer-science--cs101
https://edx.org/course/introduction-computer-science-harvardx-cs50x

**General Web Courses**
https://udacity.com/course/web-development--cs253
https://udacity.com/course/full-stack-foundations--ud088
https://udacity.com/course/mobile-web-development--cs256

**Design**
https://udacity.com/course/responsive-web-design-fundamentals--ud893
https://udacity.com/course/responsive-images--ud882

**HTML**
https://udacity.com/course/intro-to-html-and-css--ud304
https://udacity.com/course/html5-canvas--ud292

**CSS**
https://udacity.com/course/intro-to-html-and-css--ud304

**Javascript**
https://udacity.com/course/javascript-basics--ud804
https://udacity.com/course/object-oriented-javascript--ud015
https://udacity.com/course/intro-to-ajax--ud110

**JQuery**
https://udacity.com/course/intro-to-jquery--ud245

**Databases**
https://udacity.com/course/intro-to-relational-databases--ud197

**Advanced**
https://udacity.com/course/html5-game-development--cs255

----

**Comment by TammyTee** [comment]
✅ Reviewed and added the courses that were relevant.

@mattstauffer - Udacity tends to be pretty legit and they carry good content. There is also a process involved with becoming one of their instructors. I would be a little less receptive if these were Udemy resources.
