### ISSUE TITLE
Write a command to back up all the core data (resources, modules, glossary, etc.) into seed files in the git repo

### ISSUE THREAD

**Issue by mattstauffer** [tighten/onramp#239]
Currently this is all managed in the database, but I really think of it as part of the core concept of the app, so I'd love people to get this seeded when they spin up a new version.

So I imagine something like `php artisan generate:seeds-from-db` that re-creates our seeds from the database state of resources, modules, terms, tracks, and probably other things like the linkage between terms and modules, etc.

**Comment by skylerkatz** [comment]
@mattstauffer would something as rudimentary as a mysql dump work for this type of command, or would you want it to generate some sort of json file that could be loaded and models generated/saved to the database from there?

**Comment by mattstauffer** [comment]
I think I meant like JSON files. So we could have JSON files in the repo right now that's the current state of all of the learning materials, and then update the seeders to pull from those files.. and then we generate a command that re-generates those files from the current state of the database, so people seeding the app on their local machines in the future get a more robust version of the content.
