### ISSUE TITLE
Make it possible for contributors who don't have a Nova license to run the site locally

### ISSUE THREAD

**Issue by mattstauffer** [tighten/onramp#241]
https://twitter.com/stauffermatt/status/1279106042287271936

**Comment by mattstauffer** [comment]
Might not be viable because of how it would affect `composer.lock`, trying to think of / figure out clever solutions

**Comment by mattstauffer** [comment]
Previous title was "Move Nova into `suggests` and then update instructions to talk about bringing it back".. not sure if that's actually the best solution?

**Comment by mattstauffer** [comment]
Wait.. this is a duplicate of #237? Geez. My brain.

**Comment by mattstauffer** [comment]
OK, for now I'm just gonna do `suggests` for now. I had a plan to try out all the other suggestions, but I'm just gonna do this at the moment.

**Comment by mattstauffer** [comment]
... and nevermind, because then all the packages that depend on it would fail. :sigh:

**Comment by nagi1** [comment]
I just want to translate, no need for nova!

Do you have reasanable steps to go just for translations?

**Comment by mattstauffer** [comment]
Nope. Honestly I don't yet.

**Comment by darkboywonder** [comment]
This issue is fixed by #380. Closing.
