### ISSUE TITLE
Add a new background experiences

### ISSUE THREAD

**Issue by FoksVHox** [tighten/onramp#256]
I think it should be possible for new Laravel developers, who know the basics of Laravel, to join Onramp. Right now the only background experiences that relate somewhat to them are WordPress developers. 

I feel like this isn't covering everyone that wants to use Onramp.
![image](https://user-images.githubusercontent.com/37844753/89026208-90389000-d328-11ea-9e7e-399664273f3e.png)

**Comment by TammyTee** [comment]
Hi @FoksVHox. Thank you for your suggestion!

Programmers who are new to Laravel could easily follow our "New to Programming" track and still get the full benefits of using Onramp to sharpen their Laravel skills by checking out some of the intermediate and advanced modules. 

Still, we would love to hear if you have any suggestions for newer resources or modules that you think someone with this experience would be looking for.
