### ISSUE TITLE
Address performance issues found with Google Lighthouse

### ISSUE THREAD

**Issue by dhicking** [tighten/onramp#260]
<img width="774" alt="image" src="https://user-images.githubusercontent.com/828307/91090333-e399b780-e622-11ea-971c-a071189f02d1.png">

Lighthouse recommends the following

- [x] Eliminate render-blocking resources (specifically calls out the Work+Sans font being loaded from Google Fonts and https://onramp.dev/css/app.css?id=fada00fcb9591cc095a9

- [x] Remove unused CSS (same CSS file as before - so maybe that CSS file isn't even needed?)

- [ ] Removed unused JS (https://onramp.dev/js/app.js?id=4a4649e3438cff8c7c6c)

**Comment by mattstauffer** [comment]
We're adding PurgeCSS to the Tailwind config.
I'm not sure why the JS is so bloat-y.. we have almost none. Definitely can trim that down.

**Comment by dhicking** [comment]
Lighthouse score is up to 99 - this feels good enough for now!
