### ISSUE TITLE
Consider ways to incorporate the glossary into individual modules

### ISSUE THREAD

**Issue by dhicking** [tighten/onramp#269]
Maybe link to specific terms on appropriate pages?

**Comment by mattstauffer** [comment]
I *think* this is built already, but we just haven't hooked it up in the database yet. So... we should probably do that 😆

**Comment by TammyTee** [comment]
@mattstauffer - now that this has been implemented, did you have any specific requests for this? In addition to the related resource links on the glossary page, did you also want terms to show on the individual module pages?

**Comment by MarcyLina** [comment]
Closing as it seems too be implemented.
