### ISSUE TITLE
Add all Laravel Podcast Season Four episodes as resources

### ISSUE THREAD

**Issue by mattstauffer** [tighten/onramp#270]

**Comment by Houbsi** [comment]
I'll take this issue on after Laracon :)

**Comment by mattstauffer** [comment]
@Houbsi Are you still planning to take this on? No worries if not, but if so, I don't want to assign it to someone else. Thanks!

**Comment by TTiger** [comment]
First time contributing to Hacktoberfest - is the protocol to ask for a ticket before just taking it?

**Comment by mattstauffer** [comment]
@TTiger Usually just claim it here (saying "I'll pick this one up!") and that's good enough!

**Comment by TTiger** [comment]
Well then, I'll pick this one up !
