### ISSUE TITLE
Suggested Resources

### ISSUE THREAD

**Issue by nkeena** [tighten/onramp#272]
Here are some suggested resources that I think would be very helpful:

## Bonus - Basic DevOps

Paid video courses:
[Servers for Hackers - Scaling Laravel](https://courses.serversforhackers.com/scaling-laravel)

## Intermediate - SQL and Databases

Paid video courses:
[Eloquent Performance Patterns](https://eloquent-course.reinink.ca/)

## Advanced - Laravel Package Development

Paid video courses:
[Laravel Package Training](https://spatie.be/videos/laravel-package-training)
[PHP Package Development](https://phppackagedevelopment.com/)

Free articles:
[Laravel Package Development](https://laravelpackage.com/)

## Advanced - Enterprise Applications

Paid video courses:
[Laravel Beyond CRUD](https://spatie.be/videos/laravel-beyond-crud)

**Comment by dillingham** [comment]
There is no paid js beginner. es6.io is kind of the go to for that.

**Comment by TammyTee** [comment]
@dillingham @nkeena - Thank you both for your suggestions! 🎉  We've gone ahead and added the beginner and intermediate resources to the site. #377 will add in the advanced resources once we have those modules created.
