### ISSUE TITLE
Upgrade Nova

### ISSUE THREAD

**Issue by mattstauffer** [tighten/onramp#278]

**Comment by faxblaster** [comment]
Unless I'm missing something, or mistaken, it looks like this is done.

`composer.json`

<img width="506" alt="Screen Shot 2020-09-18 at 1 51 22 PM" src="https://user-images.githubusercontent.com/4378273/93634401-29456800-f9b6-11ea-9b2d-493e0fdaa2ed.png">


<img width="741" alt="Screen Shot 2020-09-18 at 1 50 59 PM" src="https://user-images.githubusercontent.com/4378273/93634402-29ddfe80-f9b6-11ea-9e7d-a7aec987ab99.png">

**Comment by mattstauffer** [comment]
<img width="351" alt="image" src="https://user-images.githubusercontent.com/151829/93658329-94b82580-fa08-11ea-98b8-9b2e27c4e545.png">

The widget on the Nova dashboard says there's a `3.10.0`, and I just logged in and the Nova dashboard shows that too:

<img width="1212" alt="image" src="https://user-images.githubusercontent.com/151829/93658346-c7621e00-fa08-11ea-8c79-8c7b1fb74f7f.png">
