### ISSUE TITLE
Ideas - Experience, Git Resources

### ISSUE THREAD

**Issue by brada1703** [tighten/onramp#287]
# Experience

![image](https://user-images.githubusercontent.com/16405921/95675032-35cf7180-0bac-11eb-9636-18d64acc7b3e.png)

For background experience, maybe add a few more categories.

- Fullstack Developer (Useful material would be everything)
- Backend Developer (Useful material would be Laravel specific)

# Git Resources

I personally really like JMac's GettingGit series. He has some free as well as paid material. https://gettinggit.com/

**Comment by darkboywonder** [comment]
Hi @brada1703! Thanks for suggesting adding additional background experience options. Onramp is organized for folks to become Laravel programmers as easily and effectively as possible. Unfortunately, these options are a bit too broad for this site, but we would love to hear if you have a particular background experience or framework you're coming from that you would love to have content provided for (Drupal, Magento, .etc).

Thanks for your git resource suggestion! We went ahead and added it to the site.
