### ISSUE TITLE
Update language strings

### ISSUE THREAD

**Issue by mattstauffer** [tighten/onramp#294]
All languages need these strings updated:

"It's iterative and opinionated. It's open source and contributions are welcome, but in the end Tighten will keep it focused on the way we think folks are best prepared for a career as a Laravel developer."

is now

"Join Onramp for free today to see the technologies and processes the team at Tighten thinks are best for you to learn, and our favorite resources for learning them."

And

"Providing an easy entrance to Laravel for new developers"

is now

"Learn Laravel quickly, no matter your background."

- [x] Polski
- [x] Español
- [x] Português
- [x] Svenska
- [x] Deutsch
- [x] Dansk
- [x] Čeština
- [x] Bahasa
- [x] French

**Comment by TammyTee** [comment]
Matt found this package that we might be able to use here: [Laravel Translations Checker](https://laravel-news.com/laravel-translations-checker?utm_medium=email&utm_campaign=Laravel%2094%20Released%20Caching%20Chunks%20in%20Blade%20and%20more%20-%20402&utm_content=Laravel%2094%20Released%20Caching%20Chunks%20in%20Blade%20and%20more%20-%20402+CID_3f473fe9a10447405bc8cb3c1a80e261&utm_source=email%20marketing&utm_term=Read%20More)

**Comment by MarcyLina** [comment]
I'll take this on since I'm already in language Land
