### ISSUE TITLE
Add ability to search modules

### ISSUE THREAD

**Issue by TammyTee** [tighten/onramp#386]

**Comment by TammyTee** [comment]
Hi @Luky72069!

Thanks for your help 😄 On the module listing page for Onramp (seen [here](https://onramp.dev/en/modules)), we'd like for users to have the ability to search for modules by name. The search bar can live just above the list of modules. Here's some additional info to help you get started:

- For styling, we use [TailwindCSS](https://tailwindcss.com/docs/installation)
- You may be able to easily implement this functionality using [AlpineJS](https://alpinejs.dev/start-here) (which is already included in the codebase) and [fuse.js](https://fusejs.io/), which is a light-weight library for adding fuzzy search capabilities to an application.

**Comment by TammyTee** [comment]
Hi @Luky72069 👋🏾!

Is there anything we can assist here with on this issue?

**Comment by Luky72069** [comment]
Hello @TammyTee . 
I created pull request. Can you look at it ?
