### ISSUE TITLE
Add Laravel Translations Checker

### ISSUE THREAD

**Issue by TammyTee** [tighten/onramp#392]
[Laravel Translations Checker](https://laravel-news.com/laravel-translations-checker?utm_medium=email&utm_campaign=Laravel%2094%20Released%20Caching%20Chunks%20in%20Blade%20and%20more%20-%20402&utm_content=Laravel%2094%20Released%20Caching%20Chunks%20in%20Blade%20and%20more%20-%20402+CID_3f473fe9a10447405bc8cb3c1a80e261&utm_source=email%20marketing&utm_term=Read%20More)

**Comment by MarcyLina** [comment]
Package added 8-19-22. Now working on updating the missing phrases.
