### ISSUE TITLE
Set up email notifications for users with new content

### ISSUE THREAD

**Issue by tammytee** [tighten/onramp#451]
We should notify users when new resources have been added to the platform so that they aren't missing out on new content. It would helpful if this is sent out in more of a "digest" format, rather than directly after the new content is added. 

Users should have the ability to unsubscribe from these notifications.

**Comment by tammytee** [comment]
Another nice to have for this would in-app notifications that the users can read when visiting Onramp. The in-app notifications can list new resources that have been added and other Onramp updates.

**Comment by MarcyLina** [comment]
Implemented in [this PR ](https://github.com/tighten/onramp/pull/594)
