### ISSUE TITLE
Limit the number of skills that show on a module to a max of 5

### ISSUE THREAD

**Issue by TammyTee** [tighten/onramp#477]
## Summary

**Todo**

- [ ] Add a limit to the number of skills a module can have/show on a module
- [x] Audit the existing resources

**Modules to audit**
- Laravel Basics For WordPress Developers
- Basic Testing (has 5 exactly)
- Basic JavaScript
- Laravel Basics
- Beginning PHP

**Idea**

Rather than removing the extra skills, we could make it so the user sees a small `+ 3 more` bubble or something similar that can be clicked to see the remaining skills. We may also want to consider making them smaller so they don't take up so much space?

### Current Example
<img width="1474" alt="image" src="https://user-images.githubusercontent.com/8689444/191997862-5a2fad7e-8483-4d66-b82c-61dbfa27e336.png">

**Comment by LubosGangster** [comment]
Hi,

i would like to help with that issue. Can you assign it to me ?

**Comment by TammyTee** [comment]
Hi @LubosGangster!

Thanks for your help 😄. For this issue, we'd like to limit the number of skills shown on a module by default to prevent the "Overview" and "Skills" sections from getting too big. The issue title mentions a max of five, but I think this would actually work great if it's limited to four, with the fifth badge being a button users can click to see the remaining skills.

The summary above lists all of the modules that currently have 5 or more skills.

**Here are some acceptance criteria for this issue:**
- display four skills on a module detail page by default
- if a module has more than four skills, add a fifth badge that will show/hide the remaining skills
- the fifth badge should show the number of skills that are hidden

**Example:**
<img width="1501" alt="image" src="https://user-images.githubusercontent.com/8689444/193661866-a1f8cea1-22a5-4aa7-be23-61230673513a.png">

Here are additional details on [how to contribute to this repo](https://github.com/tighten/onramp/blob/main/contributing.md). Happy coding 😃!

**Comment by LubosGangster** [comment]
hi @TammyTee ,


i created PR -> https://github.com/tighten/onramp/pull/485 


Can you review it ?
