### ISSUE TITLE
Login through github does not seem to work

### ISSUE THREAD

**Issue by attisimon** [tighten/onramp#580]
Hello!

I accepted to connect through GitHub, but cannot seem to be able to log in. I stay on the same login page and there is no hint in the console or network activity in the browser. Github responds with 302 Found, but Onramp stays the same, not logged in.

Is there an additional step I need to do or is this something that needs an update?

Thanks!

**Comment by mattstauffer** [comment]
Hey @attisimon! Sorry for the delay; I haven't been able to reproduce your issue but would love to make sure we can help you with it. Let me know if it's still persisting for you!

**Comment by attisimon** [comment]
Hey @mattstauffer!

Only today I got to check this again and it still happens.

What I did today was this:
- I was already logged into GitHub on this browser
- I went to https://onramp.dev/en/login and clicked on "Login or Register with :octocat:"
- the pages seems to briefly reload, but nothing else happens (there is not error in the console log)

- then I logged out of GitHub
- I went to https://onramp.dev/en/login and clicked on "Login or Register with :octocat:"
- the page redirected to GitHub, asking me to login and then to approve the authorization
- I am redirected back to the login page, seeing the login form, just as before
- clicking on "Login or Register with :octocat:" will briefly reload the page, but I am not logged in

**Comment by MarcyLina** [comment]
Hi @attisimon! 

I am also having trouble recreating this bug. Can you tell me what browser & version you are using as well as your OS? Thanks!

**Comment by mattstauffer** [comment]
@attisimon Thanks so much for your patience. Would you mind trying again? We added a little error notification that you hopefully will see when it fails, and also added additional logging so we can try to get to the core of the issue. Thanks!!

**Comment by attisimon** [comment]
Hi @mattstauffer!

I have tested again, using Google Chrome on Linux, Version 125.0.6422.141 (Official Build) (64-bit).
The behavior is the same. I have emptied everything from the cache before testing.
The odd thing is that there is no clue in the console about what is happening.
There is a recording further down. After stopping the recording, I also checked the network tab, nothing strange there either.

[Screencast_20240604_142945.webm](https://github.com/tighten/onramp/assets/7713006/4c662c04-cb32-42a2-959e-b729a6f1ba21)

**Comment by mattstauffer** [comment]
@attisimon I _think_ we've fixed it finally? Thank you so much for the video!! @sperelson we tested it a bunch of times and couldn't reproduce it, but after testing it in an incognito browser we were finally able to reproduce it and it was indeed the missing slash in the `GITHUB_REDIRECT_URL`. Thank you so much for your investigation!

**Comment by mattstauffer** [comment]
@sperelson haha I saw that error, and fixed it. Sorry about that! https://github.com/tighten/onramp/commit/f19089f64b33fe6a60499e34d307ff114ad83a29

Glad to see you were able to log in, and I look forward to meeting you! Make sure you get a Tighten pin from me--I owe you that at the very minimum for your help here!

**Comment by attisimon** [comment]
@mattstauffer , I have cleared everything and tested again.
I am redirected to GitHub, sign in, authorize, then redirected back to onramp.dev and get this error:
![onramp-github-error](https://github.com/tighten/onramp/assets/7713006/dd48892b-da4f-4c31-b6e8-0fce21e35940)

The same error appears on every subsequent click on the login button.

**Comment by attisimon** [comment]
Guys, I was now able to finish the process of registering and logging in with my GitHub account. From my point of view this is fixed. Thanks everyone!

**Comment by mattstauffer** [comment]
Fantastic. @attisimon and @sperelson thank you *so much* for helping us debug this issue!!
